In [1]:
import pandas as pd

In [35]:
df = pd.read_excel(r"D:\Customer Call List (1).xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [36]:
df = df.drop(columns = "Not_Useful_Column", errors = "ignore")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [42]:
#df["Last_Name"] = df["Last_Name"].str.lstrip("/")
#df["Last_Name"] = df["Last_Name"].str.lstrip("...")
#df["Last_Name"] = 
df["Last_Name"] = df["Last_Name"].str.rstrip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [52]:
#df = df["Phone_Number"].str.replace('[^a-zA-Z0-9]', '', regex = True)


#df["Phone_Number"].apply(lambda x: x[0:3] +'-' +x[3:6]+'-' +x[6:10])
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

In [56]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] +'-' +x[3:6]+'-' +x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [71]:
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--', '')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--', '', regex = False)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [106]:
df[["Street Address", "States", "Zipcode"]] = df["Address"].str.split(',',n=2, expand=True)
df

ValueError: Columns must be same length as key

In [107]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,States,Zipcode,Address
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,,
18,1019,Creed,Braton,,N/a,Y,N/a,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,

In [108]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,States,Zipcode,Address
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,,
18,1019,Creed,Braton,,N/a,Y,N/a,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,

In [109]:
df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,States,Zipcode,Address
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,,
18,1019,Creed,Braton,,N/a,Y,N/a,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,

In [114]:
df.drop(df[df["Do_Not_Contact"] == 'Y'].index, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,States,Zipcode,Address
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,

In [116]:
df.drop(df[df["Phone_Number"] == ''].index, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,States,Zipcode,Address
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,

In [119]:
df = df.reset_index(drop = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,States,Zipcode,Address
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,,
6,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,
10,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,,